[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.GAME.round_resets.blind_choices.Boss = get_new_boss()"
position = "after"
payload = '''
G.P_CENTERS.e_nrios_prismatic.in_shop = false
'''
match_indent = true